# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuzzy_interface.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fuzzy_window(object):
    def setupUi(self, fuzzy_window):
        fuzzy_window.setObjectName("fuzzy_window")
        fuzzy_window.resize(721, 508)
        fuzzy_window.setMaximumSize(QtCore.QSize(722, 509))
        self.centralWidget = QtWidgets.QWidget(fuzzy_window)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.next0Button = QtWidgets.QPushButton(self.page_0)
        self.next0Button.setGeometry(QtCore.QRect(620, 400, 75, 23))
        self.next0Button.setObjectName("next0Button")
        self.label = QtWidgets.QLabel(self.page_0)
        self.label.setGeometry(QtCore.QRect(10, 0, 61, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page_0)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 581, 71))
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(self.page_0)
        self.label_14.setGeometry(QtCore.QRect(400, 100, 291, 251))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("real_image.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(self.page_0)
        self.label_13.setGeometry(QtCore.QRect(50, 100, 281, 251))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("diagram.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_2 = QtWidgets.QLabel(self.page_1)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.label_2.setObjectName("label_2")
        self.next1Button = QtWidgets.QPushButton(self.page_1)
        self.next1Button.setGeometry(QtCore.QRect(620, 400, 75, 23))
        self.next1Button.setObjectName("next1Button")
        self.prev1Button = QtWidgets.QPushButton(self.page_1)
        self.prev1Button.setGeometry(QtCore.QRect(0, 400, 101, 23))
        self.prev1Button.setObjectName("prev1Button")
        self.label_4 = QtWidgets.QLabel(self.page_1)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 331, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_1)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 251, 16))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.page_1)
        self.label_11.setGeometry(QtCore.QRect(20, 50, 221, 111))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_1)
        self.label_12.setGeometry(QtCore.QRect(26, 216, 221, 131))
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label_6.setObjectName("label_6")
        self.next2Button = QtWidgets.QPushButton(self.page_2)
        self.next2Button.setGeometry(QtCore.QRect(620, 400, 75, 23))
        self.next2Button.setObjectName("next2Button")
        self.prev2Button = QtWidgets.QPushButton(self.page_2)
        self.prev2Button.setGeometry(QtCore.QRect(0, 400, 101, 23))
        self.prev2Button.setObjectName("prev2Button")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 311, 16))
        self.label_10.setObjectName("label_10")
        self.Start_Button = QtWidgets.QPushButton(self.page_2)
        self.Start_Button.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.Start_Button.setObjectName("Start_Button")
        self.label_ready = QtWidgets.QLabel(self.page_2)
        self.label_ready.setGeometry(QtCore.QRect(280, 280, 341, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_ready.setFont(font)
        self.label_ready.setTextFormat(QtCore.Qt.AutoText)
        self.label_ready.setObjectName("label_ready")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(50, 60, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.prev3Button = QtWidgets.QPushButton(self.page_3)
        self.prev3Button.setGeometry(QtCore.QRect(0, 400, 101, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev3Button.sizePolicy().hasHeightForWidth())
        self.prev3Button.setSizePolicy(sizePolicy)
        self.prev3Button.setObjectName("prev3Button")
        self.next3Button = QtWidgets.QPushButton(self.page_3)
        self.next3Button.setGeometry(QtCore.QRect(620, 400, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next3Button.sizePolicy().hasHeightForWidth())
        self.next3Button.setSizePolicy(sizePolicy)
        self.next3Button.setObjectName("next3Button")
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 691, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.next3Button_2 = QtWidgets.QPushButton(self.page_4)
        self.next3Button_2.setGeometry(QtCore.QRect(610, 390, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next3Button_2.sizePolicy().hasHeightForWidth())
        self.next3Button_2.setSizePolicy(sizePolicy)
        self.next3Button_2.setObjectName("next3Button_2")
        self.prev3Button_2 = QtWidgets.QPushButton(self.page_4)
        self.prev3Button_2.setGeometry(QtCore.QRect(10, 390, 101, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev3Button_2.sizePolicy().hasHeightForWidth())
        self.prev3Button_2.setSizePolicy(sizePolicy)
        self.prev3Button_2.setObjectName("prev3Button_2")
        self.pushButton = QtWidgets.QPushButton(self.page_4)
        self.pushButton.setGeometry(QtCore.QRect(40, 60, 99, 27))
        self.pushButton.setObjectName("pushButton")
        self.label_15 = QtWidgets.QLabel(self.page_4)
        self.label_15.setGeometry(QtCore.QRect(40, 20, 231, 17))
        self.label_15.setObjectName("label_15")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 140, 161, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        fuzzy_window.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(fuzzy_window)
        self.mainToolBar.setObjectName("mainToolBar")
        fuzzy_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(fuzzy_window)
        self.statusBar.setObjectName("statusBar")
        fuzzy_window.setStatusBar(self.statusBar)

        self.retranslateUi(fuzzy_window)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(fuzzy_window)

    def retranslateUi(self, fuzzy_window):
        _translate = QtCore.QCoreApplication.translate
        fuzzy_window.setWindowTitle(_translate("fuzzy_window", "proba"))
        self.next0Button.setText(_translate("fuzzy_window", "Next Step"))
        self.label.setText(_translate("fuzzy_window", "Step 1"))
        self.label_3.setText(_translate("fuzzy_window", "Put the vehicle on the camera 3 , position -1400, 600. Use the floor tiles as a reference"))
        self.label_2.setText(_translate("fuzzy_window", "Step 2"))
        self.next1Button.setText(_translate("fuzzy_window", "Next Step"))
        self.prev1Button.setText(_translate("fuzzy_window", "Previous Step"))
        self.label_4.setText(_translate("fuzzy_window", "Connect the vehicle using the power cord"))
        self.label_5.setText(_translate("fuzzy_window", "Set the power source to 10 V 3A Vcc"))
        self.label_11.setText(_translate("fuzzy_window", "TextLabel"))
        self.label_12.setText(_translate("fuzzy_window", "TextLabel"))
        self.label_6.setText(_translate("fuzzy_window", "Step 3"))
        self.next2Button.setText(_translate("fuzzy_window", "Next Step"))
        self.prev2Button.setText(_translate("fuzzy_window", "Previous Step"))
        self.label_7.setText(_translate("fuzzy_window", "Do you want to start the calibration process?"))
        self.label_10.setText(_translate("fuzzy_window", "The vehicle is going to do some movements"))
        self.Start_Button.setText(_translate("fuzzy_window", "Start"))
        self.label_ready.setText(_translate("fuzzy_window", "Calibration finished. Click on next to continue"))
        self.label_8.setText(_translate("fuzzy_window", "Stage 4"))
        self.label_9.setText(_translate("fuzzy_window", "Calibration results"))
        self.prev3Button.setText(_translate("fuzzy_window", "Previous Step"))
        self.next3Button.setText(_translate("fuzzy_window", "Finish test"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("fuzzy_window", "FWD Left"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("fuzzy_window", "FWD Right"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("fuzzy_window", "Turn Left"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("fuzzy_window", "Turn Right"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("fuzzy_window", "C0"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("fuzzy_window", "C1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("fuzzy_window", "C2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("fuzzy_window", "C3"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("fuzzy_window", "C4"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("fuzzy_window", "C5"))
        self.next3Button_2.setText(_translate("fuzzy_window", "Finish test"))
        self.prev3Button_2.setText(_translate("fuzzy_window", "Previous Step"))
        self.pushButton.setText(_translate("fuzzy_window", "Start test"))
        self.label_15.setText(_translate("fuzzy_window", "Test the straight line coefficients"))
        self.pushButton_2.setText(_translate("fuzzy_window", "Save the coefficients"))

